/*
 * This source file was generated by the Gradle 'init' task
 */
package com.acme;

public class App {
    private static final ProjectInfoProvider projectInfoProvider = new ProjectInfoProvider();

    public static void main(String[] args) {
        System.out.println(projectInfoProvider.getVersion());
    }
}
